from pyrens.runtime import *
myhash1 = hash_("key1",list_(1,2,3),"key2",2)
myhash2 = hash_("key3",3)
myhash3 = merge_(myhash1,myhash2)
print_(get_(myhash1,"key1"))
print_(get_(myhash1,"key2"))
print_(myhash2)
print_(myhash3)
print_(nth_(get_(myhash3,"key1"),0))
print_(count_(myhash3))
